##########
# URL VARIABLES [optional if using GitHub Pages!]
#url: https://salongie.github.io
#baseurl: /koppiepry
# location of code, the full url to your github repository
source-code: https://github.com/Salongie/koppiepry

##########
# SITE SETTINGS
title: Test artwork showcase
tagline: what I can do with all my pictures
description: "Practicing with this template to construct my own website."
# creator of the digital collection, to appear in meta tags; we typically use our GitHub usernames but feel free to just use your name
author: Salongie
# email

##########
# COLLECTION SETTINGS
metadata: critters

##########
# Site/Organization Branding 
# organization-name: "Center for Digital Inquiry and Learning (CDIL)"
# organization-link: https://cdil.lib.uidaho.edu/
# organization-logo-banner: https://cdil.lib.uidaho.edu/storying-extinction/assets/img/cdil.png
# organization-logo-nav: https://cdil.lib.uidaho.edu/assets/img/logo.png

##########
# ROBOTS EXCLUDE
# set noindex to true if you do NOT want Google to index your site
noindex: true 

##########
# BUILD SETTINGS 
#
# Note: use environment variable on build command to include analytics
# JEKYLL_ENV=production jekyll build
# ignore stuff
exclude: [docs/, Rakefile, README.md, LICENSE]
# compress CSS output
sass:
  style: compressed
